name: Build and Publish

on:
  push:
    tags: ['v*']

jobs:
  build_linux:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64 # 使用官方 manylinux 镜像
    strategy:
      matrix:
        python_version: ['cp38-cp38', 'cp39-cp39', 'cp310-cp310', 'cp311-cp311', 'cp312-cp312']
    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        run: |
          PYTHON_DIR=/opt/python/${{ matrix.python_version }}
          $PYTHON_DIR/bin/pip install build scikit-build-core pybind11
          $PYTHON_DIR/bin/python -m build --wheel --outdir dist .
          # 修复二进制标签，确保它是 manylinux 规范
          auditwheel repair dist/*.whl --wheel-dir dist/fixed
          mv dist/fixed/*.whl dist/
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-${{ matrix.python_version }}
          path: ./dist/*.whl

  build_windows_macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build wheels
        run: |
          pip install build scikit-build-core pybind11
          python -m build --wheel --outdir dist .
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./dist/*.whl

  upload_pypi:
    needs: [build_linux, build_windows_macos]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true